# Generated by Django 4.1.1 on 2022-11-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
