# Generated by Django 4.1.1 on 2022-10-27 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
