# Generated by Django 4.1.1 on 2022-10-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0004_userprofile_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='school',
        ),
    ]
