# Generated by Django 4.1.1 on 2022-11-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_slug'),
        ('socials', '0008_comment_dislikes_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='materials',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
