# Generated by Django 4.1.1 on 2022-11-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0009_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/post_photos'),
        ),
    ]
