# Generated by Django 4.1.1 on 2022-11-11 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='item',
        ),
    ]
