# Generated by Django 4.1.1 on 2022-11-11 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_rename_items_order_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='items',
        ),
    ]
